class Guwahati:
    """
    Class containing Guwahati water system data as class constants.
    """
    
    nodeinfo = {97: {'name': 'Nijeshwari PWSS',
      'type': 'location',
      'id': 97,
      'parent_id': 105,
      'instrumentations': []},
     99: {'name': 'Abstraction',
      'type': 'water_abstraction',
      'id': 99,
      'parent_id': 97,
      'instrumentations': []},
     100: {'name': 'Source',
      'type': 'source_module',
      'id': 100,
      'parent_id': 99,
      'instrumentations': [69, 70, 71]},
     101: {'name': 'Distribution',
      'type': 'water_distribution',
      'id': 101,
      'parent_id': 97,
      'instrumentations': []},
     102: {'name': 'Treated water',
      'type': 'disinfection_module',
      'id': 102,
      'parent_id': 101,
      'instrumentations': [73, 75, 76, 77, 78]},
     103: {'name': 'Storage',
      'type': 'storage_module',
      'id': 103,
      'parent_id': 101,
      'instrumentations': [79]},
     104: {'name': 'Outlet',
      'type': 'outlet_module',
      'id': 104,
      'parent_id': 101,
      'instrumentations': [85, 83, 82, 80, 84]}}

    instrumentation_asset_info = ({69: {'tag': 'Borewell level',
   'type': 'level',
   'id': 69,
   'assets': [{'id': 79,
     'serial': 'D1004901122',
     'product_name': 'Waterpilot FMX21',
     'prod_code': 'FMX21'}],
   'specifications': 'groundwater_level',
   'value_keys': ['groundwater_level'],
   'thresholds': []},
  70: {'tag': 'Power Mains',
   'type': 'power',
   'id': 70,
   'assets': [{'id': 87,
     'serial': '2407811548',
     'product_name': 'n.a.',
     'prod_code': 'Energy meter'}],
   'specifications': 'total_kwh',
   'value_keys': ['current',
    'power_factor',
    'total_kw',
    'total_kwh',
    'voltage_avg',
    'voltage_b',
    'voltage_r',
    'voltage_y'],
   'thresholds': []},
  71: {'tag': 'ABS-Pump',
   'type': 'pump',
   'id': 71,
   'assets': [{'id': 88,
     'serial': 'Guwahati_ABS-Pump01',
     'product_name': 'n.a.',
     'prod_code': 'Pump'}],
   'specifications': 'abs_pump_on',
   'value_keys': ['abs_pump_cmd',
    'abs_pump_current',
    'abs_pump_faultcode',
    'abs_pump_mode',
    'abs_pump_on',
    'desired_state',
    'individual_pump_on'],
   'thresholds': [{'id': 46,
     'name': 'Max Current',
     'key': 'abs_pump_current',
     'unit_id': 3,
     'threshold_type': 'high',
     'notification': False,
     'automatic_event_creation': True,
     'tolerance': '0.0',
     'value': 1.2},
    {'id': 50,
     'name': 'Pump Fault (Refer description for fault codes)',
     'key': 'abs_pump_faultcode',
     'unit_id': 1138,
     'threshold_type': 'high',
     'notification': False,
     'automatic_event_creation': True,
     'tolerance': '0.0',
     'value': 0.9}]},
  73: {'tag': 'Disinfect Transmitter',
   'type': 'undefined',
   'id': 73,
   'assets': [{'id': 80,
     'serial': 'L70E7D05G00',
     'product_name': 'Liquiline CM442',
     'prod_code': 'CM442'}],
   'specifications': None,
   'value_keys': [],
   'thresholds': []},
  75: {'tag': 'Chlorine',
   'type': 'analysis',
   'id': 75,
   'assets': [{'id': 82,
     'serial': 'X3048005C00',
     'product_name': 'Memosens CCS51E',
     'prod_code': 'CCS51E'}],
   'specifications': None,
   'value_keys': ['chlorine'],
   'thresholds': [{'id': 44,
     'name': 'upper',
     'key': 'chlorine',
     'unit_id': 179,
     'threshold_type': 'high',
     'notification': False,
     'automatic_event_creation': True,
     'tolerance': '0.0',
     'value': 1.0},
    {'id': 45,
     'name': 'lower',
     'key': 'chlorine',
     'unit_id': 179,
     'threshold_type': 'low',
     'notification': False,
     'automatic_event_creation': True,
     'tolerance': '0.0',
     'value': 0.6}]},
  76: {'tag': 'Chlorine Pump',
   'type': 'pump',
   'id': 76,
   'assets': [{'id': 90,
     'serial': 'Guwahati_ChlorinePump01',
     'product_name': 'n.a.',
     'prod_code': 'Pump'}],
   'specifications': 'chlorine_tank_lsh',
   'value_keys': ['chlorine_pump_cmd',
    'chlorine_pump_on',
    'chlorine_tank_lsh',
    'chlorine_tank_lsl',
    'desired_state',
    'individual_pump_on'],
   'thresholds': []},
  77: {'tag': 'Chlorine Level Switch',
   'type': 'level',
   'id': 77,
   'assets': [{'id': 96,
     'serial': 'Chlorine-level-sw01',
     'product_name': 'n.a.',
     'prod_code': 'ChlorineLvl'}],
   'specifications': 'chlorine_tank_lsl',
   'value_keys': ['chlorine_tank_lsh', 'chlorine_tank_lsl'],
   'thresholds': []},
  78: {'tag': 'Treatment Plant Level',
   'type': 'level',
   'id': 78,
   'assets': [{'id': 83,
     'serial': 'X3007D01228',
     'product_name': 'Micropilot FMR20B',
     'prod_code': 'FMR20B'}],
   'specifications': 'tp_level',
   'value_keys': ['tp_level'],
   'thresholds': []},
  79: {'tag': 'UGR Storage Level',
   'type': 'level',
   'id': 79,
   'assets': [{'id': 84,
     'serial': 'X3007C01228',
     'product_name': 'Micropilot FMR20B',
     'prod_code': 'FMR20B'}],
   'specifications': 'ugr_level',
   'value_keys': ['ugr_level'],
   'thresholds': []},
  80: {'tag': 'Treated Water Pump',
   'type': 'pump',
   'id': 80,
   'assets': [{'id': 91,
     'serial': 'Guwahati_CEN-Pump02',
     'product_name': 'n.a.',
     'prod_code': 'Pump'}],
   'specifications': 'individual_pump_on',
   'value_keys': ['cen_pump_current',
    'cen_pump_faultcode',
    'cen_pump_mode',
    'cen_pump_on',
    'individual_pump_on'],
   'thresholds': [{'id': 51,
     'name': 'Fault code (Refer Description for fault codes)',
     'key': 'cen_pump_faultcode',
     'unit_id': 1138,
     'threshold_type': 'high',
     'notification': False,
     'automatic_event_creation': True,
     'tolerance': '0.0',
     'value': 0.9}]},
  82: {'tag': 'Outlet Flowmeter',
   'type': 'flow',
   'id': 82,
   'assets': [{'id': 85,
     'serial': 'VB007B20000',
     'product_name': 'Promag W 10, 5WBB1H, DN100 4"',
     'prod_code': '5WBB1H'}],
   'specifications': 'volumeflow',
   'value_keys': ['flow_rate', 'totalizer1', 'volumeflow'],
   'thresholds': [{'id': 48,
     'name': 'Active',
     'key': 'volumeflow',
     'unit_id': 383,
     'threshold_type': 'high',
     'notification': False,
     'automatic_event_creation': False,
     'tolerance': '0.0',
     'value': 72.0}]},
  83: {'tag': 'Valve Outlet',
   'type': 'control_valve',
   'id': 83,
   'assets': [{'id': 93,
     'serial': '523970220',
     'product_name': 'n.a.',
     'prod_code': 'MOV'}],
   'specifications': 'valveopen',
   'value_keys': ['valve_faultcode', 'valveopen'],
   'thresholds': [{'id': 52,
     'name': 'Fault code (Refer Description for codes)',
     'key': 'valve_faultcode',
     'unit_id': 1138,
     'threshold_type': 'high',
     'notification': False,
     'automatic_event_creation': True,
     'tolerance': '0.0',
     'value': 0.9}]},
  84: {'tag': 'Elevated storage level',
   'type': 'level',
   'id': 84,
   'assets': [{'id': 86,
     'serial': 'V6024221179',
     'product_name': 'Micropilot FMR10',
     'prod_code': 'FMR10'}],
   'specifications': 'esr_level',
   'value_keys': ['esr_level'],
   'thresholds': []},
  85: {'tag': 'Main Controller',
   'type': 'controller',
   'id': 85,
   'assets': [{'id': 94,
     'serial': 'A8741D1DEA0A',
     'product_name': 'n.a.',
     'prod_code': '2404267'}],
   'specifications': 'backwash_indication',
   'value_keys': ['backwash_indication',
    'battery_level',
    'battery_time',
    'grid_status',
    'plc_mode'],
   'thresholds': [{'id': 49,
     'name': 'Backwash Needed Alert',
     'key': 'backwash_indication',
     'unit_id': 1138,
     'threshold_type': 'high',
     'notification': False,
     'automatic_event_creation': True,
     'tolerance': '0.0',
     'value': 1.0}]}},
 {79: {'id': 79,
   'serial': 'D1004901122',
   'product_name': 'Waterpilot FMX21',
   'prod_code': 'FMX21'},
  87: {'id': 87,
   'serial': '2407811548',
   'product_name': 'n.a.',
   'prod_code': 'Energy meter'},
  88: {'id': 88,
   'serial': 'Guwahati_ABS-Pump01',
   'product_name': 'n.a.',
   'prod_code': 'Pump'},
  80: {'id': 80,
   'serial': 'L70E7D05G00',
   'product_name': 'Liquiline CM442',
   'prod_code': 'CM442'},
  82: {'id': 82,
   'serial': 'X3048005C00',
   'product_name': 'Memosens CCS51E',
   'prod_code': 'CCS51E'},
  90: {'id': 90,
   'serial': 'Guwahati_ChlorinePump01',
   'product_name': 'n.a.',
   'prod_code': 'Pump'},
  96: {'id': 96,
   'serial': 'Chlorine-level-sw01',
   'product_name': 'n.a.',
   'prod_code': 'ChlorineLvl'},
  83: {'id': 83,
   'serial': 'X3007D01228',
   'product_name': 'Micropilot FMR20B',
   'prod_code': 'FMR20B'},
  84: {'id': 84,
   'serial': 'X3007C01228',
   'product_name': 'Micropilot FMR20B',
   'prod_code': 'FMR20B'},
  91: {'id': 91,
   'serial': 'Guwahati_CEN-Pump02',
   'product_name': 'n.a.',
   'prod_code': 'Pump'},
  85: {'id': 85,
   'serial': 'VB007B20000',
   'product_name': 'Promag W 10, 5WBB1H, DN100 4"',
   'prod_code': '5WBB1H'},
  93: {'id': 93,
   'serial': '523970220',
   'product_name': 'n.a.',
   'prod_code': 'MOV'},
  86: {'id': 86,
   'serial': 'V6024221179',
   'product_name': 'Micropilot FMR10',
   'prod_code': 'FMR10'},
  94: {'id': 94,
   'serial': 'A8741D1DEA0A',
   'product_name': 'n.a.',
   'prod_code': '2404267'}})

